name: Zip and Release Playlist Creator on Tag

on:
  push:
    tags:
      - '*' # triggers on any tag

jobs:
  zip_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create ZIP archive of playlistcreator
        run: |
          cd script.playlistcreator
          zip -r ../playlistcreator-${TAG_NAME}.zip .

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Playlist Creator ${{ env.TAG_NAME }}
          body: |
            Automated release of script.playlistcreator for version ${{ env.TAG_NAME }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: playlistcreator-${{ env.TAG_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
